[workspace]
members = []
resolver = "3"

[workspace.dependencies]

[workspace.lints.clippy]
all = "warn"
pedantic = "warn"

[workspace.lints.rust]
unsafe_code = "deny"

[workspace.package]
edition = "2024"
public = true
version = "0.0.0"
